### ISSUE TITLE
User Roles

### ISSUE THREAD

**Issue by pkoerner** [pkoerner/expert-parakeet#1]
There shall be three user roles, roughly:

- Student: Ability to see and answer questions of their enrolled course. Can also see corrections of their own answer once they are done.
- Corrector: Ability to see and grade answers. May propose test questions.
- Lecturer: All abilities of a corrector. Can assign test questions to a test set.

**Comment by timmatussek** [comment]
Also extend user specs with role.

**Comment by timmatussek** [comment]
Administrators can be set via user id in a config file.

**Comment by jakicoll** [comment]
Fixed by #96
