### ISSUE TITLE
Create a overview of what the system is already capable of and what's missing

### ISSUE THREAD

**Issue by davrad** [pkoerner/expert-parakeet#141]
Currently in order to get an overview of what the system is already capable of, we need to read through the entire codebase. In order to onboard people faster, and to write down features, that still need to be implemented, a entry in the wiki for this would be helpful.

**Comment by iTitus** [comment]
We can use the Wiki (+markdown) for this

**Comment by iTitus** [comment]
I started here: https://github.com/pkoerner/expert-parakeet/wiki/Features

**Comment by iTitus** [comment]
This is mostly done. Some points still need clarification and discussion though.
Let me know if something is missing or add it yourself ;)
