### ISSUE TITLE
Error when trying to add new correction

### ISSUE THREAD

**Issue by iTitus** [pkoerner/expert-parakeet#152]
> Now that #130 is merged the `(get-in req [:session :user :id])` call would get "our" user id, but the git id is still available via `(get-in req [:session :user :oauth-github-id])`.
> Alternatively you could use the `get-user-by-id` db function instead of `get-user-by-git-id`

_Originally posted by @JanKneiphof in https://github.com/pkoerner/expert-parakeet/pull/133#discussion_r1292718223_

**Comment by iTitus** [comment]
![image](https://github.com/pkoerner/expert-parakeet/assets/5154317/728d0bd1-7709-4491-a0c3-649984e7eba2)

**Comment by iTitus** [comment]
This needs to be changed so it uses the get-user-by-id function and not get-user-by-github-id

**Comment by dpkass** [comment]
How did you get to that view?

**Comment by iTitus** [comment]
1. I commented out the validity check in `question_controller.clj:22`
![image](https://github.com/pkoerner/expert-parakeet/assets/5154317/cd176dff-2fc0-410e-a41f-bb5463c7eb22)

1. Then I manually browsed to `/question/1` and answered the question.
![image](https://github.com/pkoerner/expert-parakeet/assets/5154317/fcddb22f-ee83-4683-b65f-92dd417a7085)

1. Look for the log statement that tells us the `:answer/id`.
![image](https://github.com/pkoerner/expert-parakeet/assets/5154317/6cbd7d40-ca62-47c8-ada8-a071b2e8b610)

1. Browse to `/new-correction?answer-id=<answer id>`, write some feedback and submit
![image](https://github.com/pkoerner/expert-parakeet/assets/5154317/aa914f26-5096-46a7-8455-23d81068b6c6)
(you have to put the points to 1 on this question for some reason, I think that's another bug)

1. Success (?)
![image](https://github.com/pkoerner/expert-parakeet/assets/5154317/8187c4c7-4ca3-481a-93a7-554a64aa08a7)

**Comment by dpkass** [comment]
Thanks. I found a simpler way: http://localhost:8081/new-correction?answer-id=1

**Comment by iTitus** [comment]
Ah nice, some answers are in the dummy data :+1:
