### ISSUE TITLE
Selected Answer Set & Possible Solution to a Question not saved correctly

### ISSUE THREAD

**Issue by iTitus** [pkoerner/expert-parakeet#177]
- [x] question answering (#178)
- [ ] question creation (#179)

We switched from `:answer/answer` to `:answer/selected-solutions` for single-/multiple-choice questions and similarly for question creation.

https://github.com/pkoerner/expert-parakeet/blob/115ae8091cf96f687a65cc6b7038f9197b751ef9/src/clj/db.clj#L383-L395

https://github.com/pkoerner/expert-parakeet/blob/115ae8091cf96f687a65cc6b7038f9197b751ef9/test/controllers/question/question_controller_test.clj#L125-L197

**Comment by dpkass** [comment]
Just adjusted to adhere to glossary.

**Comment by dpkass** [comment]
The naming problem is solved in #180
