### ISSUE TITLE
Check OAUTH flow: Check security especially the allowed origins with CORS

### ISSUE THREAD

**Issue by timmatussek** [pkoerner/expert-parakeet#70]

**Comment by jakicoll** [comment]
Ich werde ein paar Sätze dazu schreiben
- an welcher Stelle im Projekt wir CORS brauchen
- wie es aktuell eingestellt ist und
- welche Optionen wir haben.

**Comment by jakicoll** [comment]
Dadurch, dass wir keine Trennung zwischen Frontend und Backend mehr haben, ist CORS für uns nicht mehr relevant.
