### ISSUE TITLE
OAuth Private Email Unavailabe

### ISSUE THREAD

**Issue by timmatussek** [pkoerner/expert-parakeet#77]
Even though we request the user name and email scope with Github OAuth, if the profile has these set to private we do not get them in the https://api.github.com/user call. Both values are returned as nil.

It seems to be possible to retrieve it regardless of the privacy settings via the  https://api.github.com/user/emails API.

See also: https://stackoverflow.com/questions/35373995/github-user-email-is-null-despite-useremail-scope

**Comment by JanKneiphof** [comment]
Maybe I forgot something, but is it a strict requirement for us to access the mail via github?
To identify the user in our app we could use the id that is provided by the https://api.github.com/user call
It is unique per github account and can't be changed.
And if we need to, we then could ask the user to provide their mail address within our app. 
What do you think?

**Comment by pkoerner** [comment]
Technically, we do not need to store any mail address as long as the registration requires the university identifier (Unikennung). If needed, we can always concatenate unikennung + @hhu.de to get the student's mail address.

**Comment by jakicoll** [comment]
It's a good idea to rely on the user id for identification. In contrast to the primary email adress of the account (which might change), the user id is a permanent identifier.

**Comment by jakicoll** [comment]
This would also allow us, to remove user:email from the scope of the github oauth request.

**Comment by timmatussek** [comment]
We decided we no longer need email and username from github. We will remove those from the OAuth scope. We can later request the user to provide the Unikennung on sign in.
